imports:
    - { resource: parameters.yml }
#    - { resource: params_ma27apikeyauthentication.yml }

framework:
    secret: %kernel.secret%
    assets: ~
    templating:
        engines: ['twig']
    serializer:
        enabled: true
# Config SSH Keys for LexikJWTAuthenticationBundle
lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%
